# Generated by Django 5.1.4 on 2025-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_alter_item_image_alter_item_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Description',
            new_name='Review',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
